spring.datasource.url: jdbc:mysql://localhost:3306/pubdev?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=UTC&useUnicode=true&characterEncoding=utf8
spring.datasource.username: root
spring.datasource.password: ${MYSQL_PASSWORD}
spring.datasource.sqlScriptEncoding: utf8
spring.jpa.hibernate.ddl-auto: none

spring.liquibase.enabled: true
spring.liquibase.change-log: classpath:db/changelog/db.changelog-master.xml
