spring:
  datasource:
    url: jdbc:${CLEARDB_DATABASE_URL:mysql://localhost:3306/pubdev?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=UTC&useUnicode=true&characterEncoding=utf8}
    username: root
    password: ${MYSQL_PASSWORD}
    sqlScriptEncoding: utf8

  jpa.hibernate.ddl-auto: none

  liquibase:
    enabled: true
    change-log: classpath:db/changelog/db.changelog-master.xml

  mail:
    protocol: smtp
    host: smtp.gmail.com
    port: 587
    username: sizenko.egor@gmail.com
    password: ${GMAIL_APP_PASSWORD}
    properties:
      mail.smtp:
        auth: true
        starttls.enable: true

  servlet.multipart:
    max-file-size: 50MB
    max-request-size: 50MB
    enabled: true

server.port: ${PORT:8080}

#upload parameters
uploadDir: upload
maxFileSizeInBytes: 10485760
avatarHeight: 36
avatarWidth: 36

#parameters for blog init
title: DevPub
subtitle: Рассказы разработчиков
phone: +7 903 666-44-55
email: mail@google.com
copyright: Ego-S
copyrightFrom: 2019

#length of announce in the post preview
announceLength: 100

#post requirements
titleMinLength: 3
textMinLength: 50

#BCryptPasswordEncoder strength
encoderStrength: 12

#registration-form validation parameters
usernameMinLength: 3
passwordMinLength: 6

#captcha settings
captchaImgHeight: 35
captchaImgWidth: 100
captchaMaxLength: 6
captchaLifeTimeInMinutes: 60

#comment settings
commentMinLength: 3

#
rootPage: ${ROOT_PAGE:localhost:8080}
loginChangeSuffix: /login/change-password/
