spring.datasource.url: jdbc:mysql://localhost:3306/pubdev
spring.datasource.username: root
spring.datasource.password: ${MYSQL_PASSWORD}
spring.jpa.hibernate.ddl-auto: update

#parameters for blog init
title: DevPub
subtitle: Рассказы разработчиков
phone: +7 903 666-44-55
email: mail@google.com
copyright: Ego-S
copyrightFrom: 2019